### PR TITLE
CI: Add --warning-mode=fail to Gradle build

### PR DESCRIPTION
**Pull request by EwoutH**
Added `--warning-mode=fail` to the Gradle build to let the CI fail if any warnings are thrown.

### CODE REVIEW

**Comment by BartNijland91** [comment]
I'm not a fan of letting the CI fail on warnings, there is a reason there is a distinction between the two (error and warnings). Errors are meant for immediate action, warnings can be addressed later. If for example a hot fix is needed, you don't want your CI to fail because there are some warnings that are not resolved. It would be an idea to someone show this in the PR (but not blocking). What do you think?

**Comment by EwoutH** [comment]
True, that's a legit point. The other perspective is that warnings are pretty often ignored until they become errors, for a wide range of reasons. If there are internal process to monitor and fix warnings periodically (a monthly warnings-bash session for example), this PR is moot.

Another point is that once you're warning-free, it will harder for new warnings to slip into the system. New depreciation warnings in a Gradle update could be cached faster.

Also note that this is only for internal Gradle warnings. There is a small chance that those are unintentionally triggered by things outside the build system.

**Comment by BartNijland91** [comment]
Good points as well, fixing Gradle warnings will definitely be done. I do stand by that Gradle warnings should not block the CI/CD process, at least not now in this stage of the project where quick decisions or releases have to be made. It could be a consideration when the project is in a more mature and stable state.

**Comment by EwoutH** [comment]
I tried something different: I removed the `./gradlew --warning-mode=fail` part from the normal build and test step, but added an extra step with it that only runs on scheduled builds. Then I added a scheduled build that runs every Monday morning at 06:00 UTC.

Pushes and pull request now won't fail on Gradle warnings, but the weekly job will fail. This way newly introduced depreciations can be detected quickly (as long as someone watches the CI).

**Comment by BartNijland91** [comment]
Thanks for your input @EwoutH! I discussed this internally and while this would be a okay solution, we rather not let this affect our our CI process. We will look into monitoring warnings.

**Pull request closed without merging**
